#include <gtest/gtest.h>
#include "pdf_export/FluReportBuilder.h"
#include <QVariantList>
#include <QVariantMap>
#include <QFile>
#include <QTemporaryDir>

/**
 * @brief 单元测试 - PDF报告生成器功能测试
 */

class FluReportBuilderTest : public ::testing::Test {
protected:
    void SetUp() override {
        builder = new FluReportBuilder();
        tempDir.reset(new QTemporaryDir());
        ASSERT_TRUE(tempDir->isValid());
    }
    
    void TearDown() override {
        if (builder) {
            delete builder;
            builder = nullptr;
        }
    }
    
    FluReportBuilder *builder;
    std::unique_ptr<QTemporaryDir> tempDir;
};

// 测试构造函数
TEST_F(FluReportBuilderTest, Construction) {
    EXPECT_NE(builder, nullptr);
}

// 测试属性设置
TEST_F(FluReportBuilderTest, SetProperties) {
    builder->setTitle("Test Report");
    builder->setAuthor("Test Author");
    builder->setCompany("Test Company");
    
    // 验证属性已设置
    EXPECT_EQ(builder->getTitle(), "Test Report");
    EXPECT_EQ(builder->getAuthor(), "Test Author");
    EXPECT_EQ(builder->getCompany(), "Test Company");
}

// 测试默认边距设置
TEST_F(FluReportBuilderTest, DefaultMargins) {
    EXPECT_EQ(builder->getMarginLeft(), 20);
    EXPECT_EQ(builder->getMarginRight(), 20);
    EXPECT_EQ(builder->getMarginTop(), 20);
    EXPECT_EQ(builder->getMarginBottom(), 20);
}

// 测试页面大小设置
TEST_F(FluReportBuilderTest, PageSize) {
    builder->setPageWidth(210);   // A4
    builder->setPageHeight(297);
    
    EXPECT_EQ(builder->getPageWidth(), 210);
    EXPECT_EQ(builder->getPageHeight(), 297);
}

// 测试字体设置
TEST_F(FluReportBuilderTest, FontSettings) {
    builder->setFontFamily("Arial");
    builder->setFontSize(12);
    
    EXPECT_EQ(builder->getFontFamily(), "Arial");
    EXPECT_EQ(builder->getFontSize(), 12);
}

// 测试添加封面页
TEST_F(FluReportBuilderTest, AddCoverPage) {
    builder->addCoverPage("Test Title", "Test Subtitle", "2026-02-03", "Test Author");
    // 验证没有异常抛出
    EXPECT_TRUE(true);
}

// 测试添加章节
TEST_F(FluReportBuilderTest, AddSection) {
    builder->addSection("Chapter 1");
    builder->addSection("Chapter 2");
    // 验证没有异常抛出
    EXPECT_TRUE(true);
}

// 测试添加文本
TEST_F(FluReportBuilderTest, AddText) {
    builder->addText("This is plain text content");
    builder->addText("<h2>This is a heading</h2>");
    builder->addText("<p>This is a paragraph</p>");
    // 验证没有异常抛出
    EXPECT_TRUE(true);
}

// 测试添加表格
TEST_F(FluReportBuilderTest, AddTable) {
    QVariantList headers;
    headers << "Name" << "Age" << "City";
    
    QVariantList rows;
    rows.append(QVariantList{"Alice", "30", "Beijing"});
    rows.append(QVariantList{"Bob", "25", "Shanghai"});
    rows.append(QVariantList{"Charlie", "35", "Guangzhou"});
    
    builder->addTable(headers, rows);
    // 验证没有异常抛出
    EXPECT_TRUE(true);
}

// 测试添加分页符
TEST_F(FluReportBuilderTest, AddPageBreak) {
    builder->addText("Page 1 content");
    builder->addPageBreak();
    builder->addText("Page 2 content");
    // 验证没有异常抛出
    EXPECT_TRUE(true);
}

// 测试生成PDF文件
TEST_F(FluReportBuilderTest, GeneratePdf) {
    builder->setTitle("Test Report");
    builder->setAuthor("Test Author");
    builder->addCoverPage("Test Report", "Generated by FluentUI", "2026-02-03", "Test Author");
    builder->addSection("Introduction");
    builder->addText("This is a test report.");
    
    QString outputPath = tempDir->path() + "/test_report.pdf";
    bool result = builder->generate(outputPath);
    
    EXPECT_TRUE(result);
    EXPECT_TRUE(QFile::exists(outputPath));
    
    // 验证文件有内容
    QFile file(outputPath);
    ASSERT_TRUE(file.open(QIODevice::ReadOnly));
    qint64 fileSize = file.size();
    file.close();
    EXPECT_GT(fileSize, 0);
}

// 测试生成包含表格的PDF
TEST_F(FluReportBuilderTest, GeneratePdfWithTable) {
    builder->setTitle("Data Report");
    builder->addCoverPage("Data Report", "Table Example", "2026-02-03", "Author");
    
    builder->addSection("Data Table");
    QVariantList headers;
    headers << "ID" << "Value" << "Status";
    
    QVariantList rows;
    for (int i = 1; i <= 5; ++i) {
        rows.append(QVariantList{QString::number(i), QString::number(i * 100), "Active"});
    }
    builder->addTable(headers, rows);
    
    QString outputPath = tempDir->path() + "/test_table.pdf";
    bool result = builder->generate(outputPath);
    
    EXPECT_TRUE(result);
    EXPECT_TRUE(QFile::exists(outputPath));
}

// 测试生成多页PDF
TEST_F(FluReportBuilderTest, GenerateMultiPagePdf) {
    builder->setTitle("Multi-Page Report");
    builder->addCoverPage("Multi-Page Report", "Testing Multiple Pages", "2026-02-03", "Author");
    
    for (int i = 1; i <= 3; ++i) {
        builder->addSection(QString("Section %1").arg(i));
        builder->addText(QString("<p>Content of section %1</p>").arg(i));
        
        if (i < 3) {
            builder->addPageBreak();
        }
    }
    
    QString outputPath = tempDir->path() + "/test_multipage.pdf";
    bool result = builder->generate(outputPath);
    
    EXPECT_TRUE(result);
    EXPECT_TRUE(QFile::exists(outputPath));
}

// 测试中文内容支持
TEST_F(FluReportBuilderTest, ChineseContentSupport) {
    builder->setTitle("中文报告");
    builder->setFontFamily("SimSun");
    builder->addCoverPage("电力系统报告", "潮流计算分析", "2026-02-03", "分析员");
    
    builder->addSection("第一章 概述");
    builder->addText("这是一个中文内容的测试报告。");
    
    builder->addSection("第二章 数据表格");
    QVariantList headers;
    headers << "节点号" << "电压(pu)" << "功率(MW)";
    
    QVariantList rows;
    rows.append(QVariantList{"1", "1.05", "100"});
    rows.append(QVariantList{"2", "1.02", "150"});
    builder->addTable(headers, rows);
    
    QString outputPath = tempDir->path() + "/test_chinese.pdf";
    bool result = builder->generate(outputPath);
    
    EXPECT_TRUE(result);
    EXPECT_TRUE(QFile::exists(outputPath));
}

// 测试空报告生成
TEST_F(FluReportBuilderTest, GenerateEmptyReport) {
    QString outputPath = tempDir->path() + "/empty_report.pdf";
    bool result = builder->generate(outputPath);
    
    // 即使是空报告也应该生成有效的PDF
    EXPECT_TRUE(result || !QFile::exists(outputPath));  // 可能失败
}

// 测试信号发送
TEST_F(FluReportBuilderTest, ProgressSignals) {
    builder->setTitle("Report");
    builder->addCoverPage("Test", "Subtitle", "2026-02-03", "Author");
    builder->addSection("Section 1");
    builder->addText("Content");
    
    int progressCount = 0;
    int errorCount = 0;
    
    connect(builder, &FluReportBuilder::generationProgress, [&](int p) {
        progressCount++;
    });
    
    connect(builder, &FluReportBuilder::generationError, [&](const QString &) {
        errorCount++;
    });
    
    QString outputPath = tempDir->path() + "/test_signals.pdf";
    builder->generate(outputPath);
    
    // 应该发送了至少一个进度信号
    EXPECT_GT(progressCount, 0);
    // 不应该有错误
    EXPECT_EQ(errorCount, 0);
}

// 测试重复添加内容
TEST_F(FluReportBuilderTest, MultipleAdditions) {
    for (int i = 0; i < 5; ++i) {
        builder->addSection(QString("Section %1").arg(i));
        builder->addText(QString("Text in section %1").arg(i));
    }
    
    QString outputPath = tempDir->path() + "/test_multiple.pdf";
    bool result = builder->generate(outputPath);
    
    EXPECT_TRUE(result);
}

// 测试特殊字符处理
TEST_F(FluReportBuilderTest, SpecialCharacters) {
    builder->addText("Special chars: & < > \" ' # @ $ % ^ * ( ) { } [ ]");
    builder->addText("Numbers: 0123456789");
    builder->addText("Symbols: ± × ÷ √ ∫ ∑ ∏");
    
    QString outputPath = tempDir->path() + "/test_special_chars.pdf";
    bool result = builder->generate(outputPath);
    
    EXPECT_TRUE(result);
}

// 组合测试：完整的报告生成流程
TEST_F(FluReportBuilderTest, CompleteReportGeneration) {
    // 设置报告属性
    builder->setTitle("电力系统分析报告");
    builder->setAuthor("分析部门");
    builder->setCompany("电力公司");
    builder->setFontFamily("SimSun");
    builder->setFontSize(11);
    
    // 添加封面
    builder->addCoverPage(
        "电力系统分析报告",
        "2026年2月潮流计算",
        "2026-02-03",
        "分析部门"
    );
    
    // 添加第一章
    builder->addSection("第一章 计算概述");
    builder->addText("<p>本报告主要分析电网的潮流情况。</p>");
    
    // 添加数据表格
    builder->addSection("第二章 节点数据");
    {
        QVariantList headers;
        headers << "节点号" << "电压(pu)" << "功率(MW)" << "状态";
        
        QVariantList rows;
        rows.append(QVariantList{"1", "1.050", "100.5", "正常"});
        rows.append(QVariantList{"2", "1.025", "150.3", "正常"});
        rows.append(QVariantList{"3", "1.015", "120.8", "正常"});
        
        builder->addTable(headers, rows);
    }
    
    builder->addPageBreak();
    
    // 添加第二章
    builder->addSection("第三章 线路参数");
    {
        QVariantList headers;
        headers << "线路ID" << "起点" << "终点" << "状态";
        
        QVariantList rows;
        rows.append(QVariantList{"L1", "1", "2", "运行"});
        rows.append(QVariantList{"L2", "2", "3", "运行"});
        
        builder->addTable(headers, rows);
    }
    
    // 生成PDF
    QString outputPath = tempDir->path() + "/complete_report.pdf";
    bool result = builder->generate(outputPath);
    
    EXPECT_TRUE(result);
    EXPECT_TRUE(QFile::exists(outputPath));
    
    // 验证文件大小
    QFile file(outputPath);
    ASSERT_TRUE(file.open(QIODevice::ReadOnly));
    qint64 fileSize = file.size();
    file.close();
    EXPECT_GT(fileSize, 1000);  // 至少应该有1KB
}
